# https://docs.haskellstack.org/en/stable/travis_ci/

dist: bionic
language: generic
cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

addons:
  apt:
    update: true
    packages:
      - libgmp-dev

jobs:
  include:
    - stage: Install Stack
      script:
        - export DIR=~/.local/bin
        - if [ ! -d "$DIR" ]; then mkdir -p ~/.local/bin; fi
        - export PATH=$HOME/.local/bin:$PATH
        - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
        - stack setup
    - stage: Build
      script:
        - export PATH=$HOME/.local/bin:$PATH
        - stack build
    - stage: Test
      script:
        - export PATH=$HOME/.local/bin:$PATH
        - stack test
